config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :categories
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'
  resources :orders
  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
  end
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search = params[:search]

    @products = Product.all
    @products = @products.search(@search) if @search.present?
    @products = @products.page(params[:page]).per(4)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.slim
nav.navbar.navbar-expand-lg.navbar-dark style="background-color: #FC5B31;"
  div 
    = link_to root_path, class:"navbar-brand" do 
      i.fab.fa-shopify.fa-3x
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      - if user_signed_in?
            li.nav-item
                = link_to "Product", admins_products_path, class:"nav-link"
            li.nav-item
                = link_to "Catagory", categories_path, class:"nav-link"
            li.nav-item
                = link_to "Sign Out", destroy_user_session_path, class:"nav-link", method: :delete
            li.nav-item
                = link_to "Edit Profile", edit_user_registration_path, class:"nav-link"
      - else
            li.nav-item
                = link_to "Product", admins_products_path, class:"nav-link"
            li.nav-item
                = link_to "Catagory", categories_path, class:"nav-link"
            li.nav-item
                = link_to "Sign Up", new_user_registration_path, class:"nav-link"
            li.nav-item
                = link_to "Sign In", new_user_session_path, class:"nav-link"
    form
        = form_tag admins_products_path, method: :get, class: "form-inline.my-2.my-lg-0" do
          div.row
            div.form-group.col-xs-6
              = search_field_tag 'search', @search, placeholder: 'Search', class: "form-control mr-sm-2"
            div.form-group.col-xs-6.ml-3
              = submit_tag 'Search', class: "btn btn-outline-light my-2 my-sm-0 mr-2"

app/views/home/index.slim
br
h1 Shopnee home page
.row
  .col
    = link_to orders_path do
      = button_tag 'Order list', class: 'btn btn-secondary float-right'
        i.fas.fa-list.pr-2
        | Order list

.card-deck.mt-3
  - @products.each do |product|
          .card 
            .view.zoom.overlay
              - if product.primary_image.attached?
                = image_tag product.primary_image, width: '100%', class: 'img-fluid w-100'
              - else
                .text-center
                  i.far.fa-question-circle.fa-9x.mt-2
            .card-body.text-center
              h5 = product.title
              p.small.text-muted.text-uppercase.mb-2 = product.description
              p = "Stock: #{product.stock}"
              hr
              = link_to admins_product_path(product) do 
                = button_tag 'Details', class: 'btn btn-light btn-sm mr-1 mb-2'
                  i.fas.fa-info-circle.pr-2
                  | DETAILS
              = link_to orders_new_path(:id => product.id) do 
                = button_tag 'Buy Now', class: 'btn btn-success btn-sm mr-1 mb-2'
                  i.fas.fa-shopping-cart.pr-2
                  | Buy Now
            .card-footer
              small.text-muted = "Last updated #{time_ago_in_words(product.updated_at)} ago"

.row.mt-2
  .col-6 
    = paginate @products