config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :categories
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'
  resources :orders
  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
  end
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categories_products
    has_many :products, through: :categories_products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li class="category-link">
    <%= link_to category_path(category) do %>
        <span class="badge bg-secondary"><%= category.name %></span>
    <% end %>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.slim
h1 Category List
.cointainer-fluid.py-3
    ul.list-unstyled.nav 
        = render @categories
    - if user_signed_in?
        = link_to 'New Category', new_category_path, class: 'btn btn-primary'

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>
  <%= @category.name %>
</h1>

<div class="cointainer-fluid py-3">
  <% @category.products.each do |product| %>
      <div class="card" style="width: 18 rem;">
      <div class="card-img-top">
        <i class="far fa-question-circle fa-9x"></i>
      </div>
      <div class="card-body">
          <h5><%= product.title %></h5>
          <p class="card-text"> <%= product.description%> </p>
          <%= link_to 'Info', admins_product_path(product), class:"btn btn-primary" %>
      <% if user_signed_in? %>
          <%= link_to 'Edit', edit_admins_product_path(product), class:"btn btn-secondary" %>
          <%= link_to 'Delete', admins_product_path(product), method: :delete, data: { confirm:"Are you sure?"}, class:"btn btn-danger"%>
      <% end %>
      </div>
    </div>
  <% end %>
  <br>
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-secondary' %>
    <%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' },
      class: 'btn btn-danger' %>
  <% end %>
</div>