config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :categories
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'
  resources :orders
  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
  end
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [:draft, :published, :archived]
    scope :search, -> (arg) {where("title LIKE ? or description LIKE ?", "%#{arg}%", "%#{arg}%")}
    validates :title, length: { minimum: 1 }
    validates :stock, numericality: {greater_than_or_equal_to: 0}

    has_many :categories_products
    has_many :categories, through: :categories_products

    has_one_attached :primary_image, dependent: :destroy
    validates :primary_image, content_type: [:png, :jpg, :jpeg]
    has_many_attached :supporting_images, dependent: :destroy
    validates :supporting_images, content_type: [:png, :jpg, :jpeg]

    attr_accessor :remove_primary_image, :remove_supporting_images
    after_save :purge_primary_image, if: :remove_primary_image
    private def purge_primary_image
        return unless @remove_primary_image == '1'
        primary_image.purge_later
    end

    after_save :purge_supporting_images, if: :remove_supporting_images
    private def purge_supporting_images
        return unless @remove_supporting_images == '1'
        supporting_images.purge_later
    end
end

app/controllers/admins/products_controller.rb
module Admins
  class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_product, only: %i[ show edit update destroy ]

    # GET /products or /products.json
    def index
      @search = params[:search]

      @products = Product.all
      @products = @products.search(@search) if @search.present?
      @products = @products.page(params[:page]).per(5)


      respond_to do |format|
          format.html
          format.csv {send_data generate_csv(Product.all), file_name: 'products.csv'}
      end
    end

    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line|
        attr = line.split(",").map(&:strip)
        Product.create title: attr[0], description: attr[1], stock: attr[2]
      end
      redirect_to admins_products_path
    end

    # GET /products/1 or /products/1.json
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: admins_product_path(@product) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: admins_product_path(@product) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admins_products_path, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:title, :description, :stock, :status, :primary_image, :remove_primary_image, :remove_supporting_images, :category_ids=>[], :supporting_images => [])
      end

      def generate_csv(products)
        products.map do |product|
          [product.title, product.description, product.stock, product.status, product.created_at.to_date, product.updated_at.to_date].join(',')
        end.join("\n")
      end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_form.slim
= form_with(model: [:admins, product]) do |form|
  - if product.errors.any?
    #error_explanation

    h2
      = pluralize(product.errors.count, "error")
      |  prohibited this product from being saved:
    ul
      - product.errors.each do |error|
        li
          = error.full_message
  .field.form-group
    = form.label :title
    = form.text_area :title, class:"form-control", placeholder:"Product Name"
  .field.form-group
    = form.label :description
    = form.text_area :description, class:"form-control"
  .field.form-group
    = form.label :stock
    = form.number_field :stock, class:"form-control"
  .field.form-group 
    = form.label :categories
    = form.collection_check_boxes :category_ids, Category.order(:name), :id, :name, multiple: true do |b|
      |   
      span
        = b.label(class:"check_box") do
            = b.check_box(class:"check_box")
            |   
            = b.object.name
            
  .field.form-group
    = form.label :status
    = form.select :status, Product.statuses.keys.map {|u| [u.titleize, u]}, {}, class:"form-control"
  .field.form-group
    = form.label :primary_image
    = form.file_field :primary_image, class:"form-control"
    - if product.primary_image.attached?
      br
      = image_tag product.primary_image, class: "img-fluid w-25"
      br
      = form.label :remove_primary_image
      = form.check_box(:remove_primary_image)
  .field.form-group
    = form.label :supporting_images
    = form.file_field :supporting_images, multiple: true, class:"form-control"
    - if product.supporting_images.attached?
      br
      - product.supporting_images.each do |image|
        span.ml-3 = image_tag image, class: "img-fluid w-25"
      br
      = form.label :remove_supporting_images
      = form.check_box(:remove_supporting_images)
  .actions
    = form.submit class:"btn btn-secondary"

app/views/admins/products/_product.html.erb
<div class="card" style="width: 18 rem;">
    <img class="card-img-top" src="https://www.flaticon.com/svg/vstatic/svg/2522/2522060.svg?token=exp=1616595906~hmac=7ac90bdbdd7e17ca384131ad41516b4e" alt="Card image cap">
    <div class="card-body">
        <h5><%= product.title %></h5>
        <p class="card-text"> <%= product.description%> </p>
        <%= link_to 'Info', admins_product_path(product), class:"btn btn-primary" %>
    <% if user_signed_in? %>
        <%= link_to 'Edit', edit_admins_product_path(product), class:"btn btn-secondary" %>
        <%= link_to 'Delete', admins_product_path(product), method: :delete, data: { confirm:"Are you sure?"}, class:"btn btn-danger"%>
    <% end %>
    </div>
</div>

app/views/admins/products/edit.slim
h1 Editing Product
= render 'form', product: @product

app/views/admins/products/index.slim
.row
    .col-6
        h1 Product List

.row
  .col
    = link_to admins_products_path(format: :csv) do 
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
        i.fas.fa-file-download.pr-2
        | Download CSV
  .col-3
    = link_to orders_path do
      = button_tag 'Order list', class: 'btn btn-secondary float-right'
        i.fas.fa-list.pr-2
        | Order list

.row.mt-2
    .col
        table.table.table-bordered.table-striped.table-hover
            thead.thead-dark
                tr 
                    th (style="width: 10%") Title 
                    th (style="width: 10%") Primary Image
                    th (style="width: 10%") Description 
                    th (style="width: 10%") Stock
                    th (style="width: 10%") Status
                    th (style="width: 20%") Supporting Images
                    th (style="width: 10%") Created at
                    th (style="width: 10%") Updated at
                    th (style="width: 10%") Action
            tbody
                - if user_signed_in?
                  - @products.each do |product|
                    tr
                      td = product.title
                      td
                        - if product.primary_image.attached?
                          = image_tag product.primary_image, class: "img-fluid"
                      td = product.description
                      td = product.stock
                      td = product.status.capitalize 
                      td
                        - if product.supporting_images.attached?
                          - product.supporting_images.each do |image|
                            span.ml-3 = image_tag image, class: "img-fluid", width: "50px", height: "50px"
                      td.font-weight-light = "#{time_ago_in_words(product.created_at)} Ago"
                      td.font-weight-light = "#{time_ago_in_words(product.updated_at)} Ago"
                      td
                        span = link_to admins_product_path(product) do 
                          i.fas.fa-eye
                        span.ml-3 = link_to edit_admins_product_path(product) do 
                          i.fas.fa-pen
                        span.ml-3 = link_to admins_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } do 
                          i.fas.fa-trash
                - if not user_signed_in?
                  - @products.each do |product|
                    tr
                      td = product.title
                      td
                        - if product.primary_image.attached?
                          = image_tag product.primary_image, class: "img-fluid"
                      td = product.description
                      td = product.stock
                      td = product.status.capitalize
                      td
                        - if product.supporting_images.attached?
                          - product.supporting_images.each do |image|
                            span.ml-3 = image_tag image, class: "img-fluid", width: "50px", height: "50px"
                      td.font-weight-light = "#{time_ago_in_words(product.created_at)} Ago"
                      td.font-weight-light = "#{time_ago_in_words(product.updated_at)} Ago"
                      td
                        span = link_to admins_product_path(product) do 
                          i.fas.fa-eye

.row
  .col-6 
    = paginate @products
  .col-6
    .float-right
        = link_to new_admins_product_path do 
          = button_tag 'Add new Product', class: 'btn btn-outline-dark'
            i.fas.fa-plus-square
            |  Add new Product

- if user_signed_in?
  .row
      .col
        h4.lead - Upload csv file to add the product
        = form_tag admins_products_csv_upload_path , multipart: true do
          div = file_field_tag :csv_file
          div = submit_tag :upload

app/views/admins/products/new.slim
h1 Add new product
= render 'form', product: @product

app/views/admins/products/show.slim
.jumbotron
  h1.display-4
    = @product.title
  .cointainer-fluid.py-3
    - if @product.primary_image.attached?
      img-fluid.w-25 = image_tag @product.primary_image
    ul.list-unstyled.nav
      li.category-link
        - @product.categories.each do |category|
          = link_to category do 
            span.badge.bg-secondary = category.name
  - if @product.draft?
    span.badge.badge-pill.badge-secondary
      = @product.status
  - if @product.published?
    span.badge.badge-pill.badge-info
      = @product.status
  - if @product.archived?
    span.badge.badge-pill.badge-success
      = @product.status
  hr.my-4
    = @product.description
  p
    strong
        | Stock:
    = @product.stock
  
  - if @product.supporting_images.attached?
    p
      strong Supporting Images
    br
      - @product.supporting_images.each do |image|
        span.ml-3 = image_tag image, class: "img-fluid w-25"
  br
  span
    = link_to edit_admins_product_path(@product) do 
        = button_tag 'Edit', class: 'btn bg-light'
  span.ml-3
    = link_to admins_products_path do 
        = button_tag 'Back', class: 'btn bg-light'